# Generated by Django 5.2.4 on 2025-08-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='file',
            field=models.FileField(default='', upload_to='examens/'),
            preserve_default=False,
        ),
    ]
