# Generated by Django 5.2.4 on 2025-08-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0002_exam_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='year',
            field=models.IntegerField(max_length=4),
        ),
    ]
