# Generated by Django 5.2.4 on 2025-08-16 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0003_alter_exam_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='year',
            field=models.IntegerField(max_length=4, validators=[django.core.validators.MinValueValidator(2010), django.core.validators.MaxValueValidator(2026)]),
        ),
    ]
