# Generated by Django 5.2.4 on 2025-08-16 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0005_alter_exam_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='file',
            field=models.FileField(upload_to='examens/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='exam',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2010)]),
        ),
    ]
