# Generated by Django 5.2.4 on 2025-08-17 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0006_alter_exam_file_alter_exam_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='date_upload',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2010)]),
        ),
    ]
