# Generated by Django 5.2.4 on 2025-08-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0007_exam_date_upload_alter_exam_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='branch',
            field=models.CharField(choices=[('Licence Informatique', 'Li'), ('Licence Mathematiques Informatique', 'Lmi'), ('Licence Physique Chimie', 'Lpc'), ("Licence en Sciences de l'Eau et de l'Environnement", 'Lsee'), ('Management et Informatisé des Organisations', 'Mio'), ("Management du tourisme et de l'hôtellerie", 'Mth'), ('Langues Étrangères Appliquées', 'Lea'), ('Lettres, Arts et Civilsations', 'Lac'), ('Sciences Économiques et Gestion', 'Seg'), ('Médecine et Santé', 'Mds'), ('Dentisterie', 'Dent'), ('Pharmacie', 'Pharm')], max_length=500),
        ),
        migrations.AlterField(
            model_name='exam',
            name='ufr',
            field=models.CharField(choices=[('SET', 'Set'), ('SES', 'Ses'), ('SANTE', 'Sante')], max_length=50),
        ),
    ]
