# Generated by Django 5.2.4 on 2025-09-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0008_alter_exam_branch_alter_exam_ufr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='branch',
            new_name='filiere',
        ),
        migrations.AddField(
            model_name='exam',
            name='matiere',
            field=models.CharField(choices=[('Mathématique', 'Maths'), ('Physique', 'Phy'), ('Chimie', 'Chimie'), ('Anglais', 'Ang'), ('Espagnol', 'Esp'), ('Algorithme', 'Alg'), ('Programmation orientée objet', 'Poo'), ('Asci ', 'Asci')], default='', max_length=200),
            preserve_default=False,
        ),
    ]
