# Generated by Django 5.2.4 on 2025-09-30 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0010_alter_exam_filiere_alter_exam_matiere_alter_exam_ufr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2010)]),
        ),
    ]
